##Yotube Config

import= [
    # "~/.config/alacritty/themes/catppuccin-mocha.toml"
    # "~/.config/alacritty/themes/nord.toml"
    # "~/.config/alacritty/themes/tokyo-night.toml"
    "~/.config/alacritty/themes/rose-pine.toml"
]


live_config_reload = true

[keyboard]
    bindings = [

  { key = "Left",  mods = "Alt",     chars = "\u001b[B"  },
  { key = "Right", mods = "Alt",     chars = "\u001b[F"  },
  { key = "Left",  mods = "Command", chars = "\u001b[1;2D" },
  { key = "Right", mods = "Command", chars = "\u001b[1;2C" },
  { key = "Back",  mods = "Command", chars = "\u0015"     },
  # { key = "F1",                     chars = "\u001bOP"     },
  # { key = "F2",                     chars = "\u001bOQ"     },
  # { key = "F3",                     chars = "\u001bOR"     },
  # { key = "F4",                     chars = "\u001bOS"     },
  # { key = "F5",                     chars = "\u001b[15~"   },
  # { key = "F6",                     chars = "\u001b[17~"   },
  # { key = "F7",                     chars = "\u001b[18~"   },
  # { key = "F8",                     chars = "\u001b[19~"   },
  # { key = "F9",                     chars = "\u001b[20~"   },
  # { key = "F10",                    chars = "\u001b[21~"   },
  { key = "F11",                    action = "ToggleFullscreen"   },
  # { key = "F12",                    chars = "\u001b[24~"   },

]

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium Italic"

# [[keyboard.bindings]]
# chars = "º"
# key = "Key0"
# mods = "Alt"

#[mouse.hints]
#modifiers = "Command"

#[mouse.hints.launcher]
#program = "open"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
dynamic_title = true
dynamic_padding = true
# opacity = 0.5

[window.dimensions]
columns = 120
lines = 35

[window.padding]
x = 10
y = 10

# [window.position]
# x = 0
# y = 0


[hints]

